Cres 48 set target position as angle
FRC5188/CrescendoCode pull request #11
Opened 2024-01-25 00:01 UTC by kt-h

2024-01-25 01:28 UTC, rhit-edgingza requested changes

2024-01-25 01:28 UTC, rhit-edgingza commented on src/main/java/frc/robot/hardware/shooter/RealShooterHardware.java
> +    public PIDController getAnglePidController() {
I'm nitpicky, this should be named getAnglePIDController

2024-01-26 00:24 UTC, kt-h commented on src/main/java/frc/robot/hardware/shooter/RealShooterHardware.java
> +    public PIDController getAnglePidController() {
Fixed. I'm not sure because I didn't write this line, but I worry that it was put in ShooterHardware and made its way into issues like CRES-50, so we might need to look out for that.

2024-01-26 01:26 UTC, rhit-edgingza approved these changes

2024-01-26 01:27 UTC, merged