Updated (And Hopefully Working) Vision
FRC5188/CrescendoCode pull request #36
Opened 2024-01-27 21:16 UTC by first5188

2024-01-27 21:36 UTC, first5188 commented
Okay I put in the Climber.java fix

2024-01-27 21:37 UTC, rhit-edgingza requested changes

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/hardware/intake/IntakeIOSparkFlex.java
> +    public void setIsRollerRolling(boolean isRollerRolling) {
We don't need this method

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> -  public void setClimberSpeed(double speed) {
Please fix the code so we don't have any of this commented out

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/intake/commands/CmdIntakeRollersSpit.java
> -        _intakeSubsytem.setRollerSpeedSpit();
This command is incorrect now, please put back in the original code that runs the rollers

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/intake/commands/CmdIntakeSetPosition.java
> -        _intakeSubsystem.setIntakePosition(_intakePosition);
You're missing the call to the subsystem again

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/intake/commands/CmdIntakeStartRollersAcquire.java
> -        _intakeSubsystem.setRollerMotorSpeedAcquire();
Missing subsystem call

2024-01-27 21:37 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/intake/commands/CmdIntakeStopRollers.java
> -        _intakeSubsystem.stopRollerMotor();
Missing subsystem call

2024-01-28 17:53 UTC, mitchgres commented
Whenever the fixed tests are put into main we can fix the commented out test but since we aren't using sim-classes anymore the tests being commented out is needed for it to build.

2024-01-30 18:34 UTC, rhit-edgingza approved these changes

2024-01-30 18:35 UTC, merged