Current Position In Degrees
FRC5188/CrescendoCode pull request #9
Opened 2024-01-24 01:17 UTC by mitchgres

I also added the configuration for the angle encoder.

2024-01-24 15:59 UTC, rhit-edgingza requested changes

2024-01-24 15:59 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private final DutyCycleEncoder _angleEncoder = configEncoder(new DutyCycleEncoder(0));
We are not creating any hardware inside of subsystems anymore, it interferes with our ability to run tests. Any new piece of hardware for the shooter (this includes motors, sensors, PID controllers, etc) needs to be added to ShooterHardware, RealShooterHardware, and SimShooterHardware. There are examples of how to do this in those files already. The port for the encoder also should be a constant, which goes in HardwareConstants.java, which is also in the hardware folder.

2024-01-24 15:59 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private static final float ANGLE_ENCODER_OFFSET_FOR_ROBOT_BASE = 0;
In an effort to keep subsystems not clogged with constants, each subsystem has its own constants file in its folder. Please put this constant in there. Also, please use double, not float, for the type

2024-01-24 15:59 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +  private DutyCycleEncoder configEncoder(DutyCycleEncoder encoder) {
Configs will work without you needing to return them. So this method doesn't require an input (just use the getter from _hardware that you'll be adding to get the encoder object) or an output. When you call those methods, the config is applied to the object that we already have access to, so there's no reason to return it.

2024-01-25 21:55 UTC, rhit-edgingza requested changes

2024-01-25 21:55 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +          "It's impossible for the encoder to be this value. There must be a hardware error. Shut down this subsystem to not break everything.");
We don't want to do this in this way. The stops we have here are soft stops, in all reality, a PID controlling this motor may go slightly beyond these stops as it fluctuates, which is ok since we set soft stops well before hard stops where things start to break. So throwing an exception here to stop the code will happen quite frequently if we have a setpoint near these boundaries. If you really want to have this sort of mechanism in place, add in additional stops that are 5~10 degrees beyond these stops that would cause the code to crash

2024-01-25 21:55 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +      return Rotation2d.fromRotations(encoderValueAsRotations).getDegrees();
We don't want to do a conversion like this between rotations and degrees because we have no control over what constitutes 0. In this case, 0 would correspond to the 0 position of the encoder, but recall that our 0 is likely to be the position of the shooter when it is parallel to the ground. We should approach this similarly to last year, where we had two constants for our max and our min positions in degrees with their values being the value of the encoder at that position, then we figured out the ratio of encoder outputs to degrees by dividing the difference between the two positions in degrees by the difference between the two positions in encoder output. Let's have that calculation be a constant that gets calculated at the top of this class and then to return the encoder position in degrees you can multiply the encoder output by that ratio.

2024-01-25 21:55 UTC, rhit-edgingza commented on src/main/java/frc/robot/subsystems/shooter/ShooterConstants.java
> +    public static final double MAXIMUM_ANGLE_ENCODER_TURNS = 10;
Absolute encoders aren't like potentiometers, we only get one rotation before they roll over. Instead, have these be in degrees, which will make more sense to people when they use them

2024-01-25 21:55 UTC, rhit-edgingza commented on src/test/java/shooter/GetCurrentPositionInDegreesTests.java
> +package shooter;
Only keep these tests if you add the extra stop constants I mentioned above. If you do, you are missing a case based on BVA. You should test right at the boundaries on both sides, so the first test should be testing one boundary and you should add one more test to test the other boundary

2024-01-26 01:24 UTC, rhit-edgingza requested changes

2024-01-26 01:24 UTC, rhit-edgingza commented on src/test/java/shooter/GetCurrentPositionInDegreesTests.java
> +    void testGetCurrentPositionInDegrees_withTurnsOutput_expectDegrees() {
you're still missing a test. You need to check that the bounds that you made for throwing an exception work correctly. please write a test that checks just inside and outside MAXIMUM_ANGLE_ENCODER_TURNS + 0.1 and just inside and outside MINIMUM_ANGLE_ENCODER_TURNS - 0.1

2024-01-26 17:24 UTC, rhit-edgingza approved these changes

2024-01-26 17:37 UTC, mitchgres commented
Currently working on resolving these merge conflicts. Shouldn't be too bad, and I'll merge into main whenever it builds.

2024-01-26 17:54 UTC, merged